export { Login } from './auth/login';
export { DashBoard } from './app/dashboard';
export { UserManagement } from './app/userManagement';
export { Screen } from './app/screen';
export { AssignRole } from './app/assignrole';
export { ForgotPassword } from './auth/forgotPassword';
export { Report } from './app/reports'
export { Userlogin } from './auth/userlogin'
export { Setting } from './app/setting'
export { AssignPermission } from './app/assignPermission';
export { Permission } from './app/permission';
